name: Generate new image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: slackware/base

    steps:
      - name: Download SlackBuild
        run: |
          wget --no-check-certificate -O- https://slackbuilds.org/slackbuilds/15.0/system/powershell.tar.gz | tar -xz

      - name: Download PowerShell
        working-directory: powershell
        run: |
          source ./powershell.info
          wget --no-check-certificate $DOWNLOAD_x86_64

      - name: Build Package
        working-directory: powershell
        env:
          TAG: _pkg
          OUTPUT: /opt
          PKGTYPE: txz
        run: ./powershell.SlackBuild
